name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Aqui é onde o token é passado
          
      # Se você for fazer push ou commits no repositório, o token deve ter permissões adequadas
      - name: Push changes
        run: |
          git add .
          git commit -m "Automated commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Aqui o token é usado para autenticação
